import { parseYouTubeVideoId } from "@/lib/youtube";

export type YoutubeTranscriptResult = {
  transcript: string;
  durationSec: number | null;
  title?: string;
};

const TRANSCRIPT_BASE =
  process.env.YOUTUBE_TRANSCRIPT_AI_BASE?.trim() ||
  "https://youtube-transcript.ai/transcript";

const MAX_TRANSCRIPT_CHARS = 20_000;

/** Parse `3:27` or `1:02:15` → seconds. */
export function parseClockDuration(raw: string): number | null {
  const parts = raw
    .trim()
    .split(":")
    .map((p) => Number(p));
  if (parts.some((n) => !Number.isFinite(n) || n < 0)) return null;
  if (parts.length === 2) return Math.round(parts[0]! * 60 + parts[1]!);
  if (parts.length === 3) {
    return Math.round(parts[0]! * 3600 + parts[1]! * 60 + parts[2]!);
  }
  return null;
}

export function parseTranscriptAiDocument(markdown: string): YoutubeTranscriptResult | null {
  const text = markdown.replace(/\r\n/g, "\n").trim();
  if (text.length < 40) return null;

  const titleMatch = text.match(/^#\s*Transcript:\s*(.+)$/m);
  const title = titleMatch?.[1]?.trim() || undefined;

  const durationMatch = text.match(/Duration:\s*([\d:]+)/i);
  const durationSec = durationMatch
    ? parseClockDuration(durationMatch[1]!)
    : null;

  let body = text;
  const section = text.split(/^##\s*Transcript\s*$/im);
  if (section.length >= 2) {
    body = section.slice(1).join("\n");
  }

  body = body
    .replace(/^Generated by https?:\/\/youtube-transcript\.ai.*$/gim, "")
    .replace(/^Interactive version \(ask the video.*$/gim, "")
    .replace(/^\[[\d:]+\]\s*/gm, "")
    .replace(/\[[^\]]*♪[^\]]*\]/g, " ")
    .replace(/[♪♫]+/g, " ")
    .replace(/\[\s*\]/g, " ")
    .replace(/\s+/g, " ")
    .trim();

  if (body.length < 40) return null;

  return {
    transcript: body.slice(0, MAX_TRANSCRIPT_CHARS),
    durationSec,
    title,
  };
}

export async function fetchYoutubeTranscript(
  rawUrl: string,
): Promise<YoutubeTranscriptResult> {
  const videoId = parseYouTubeVideoId(rawUrl);
  if (!videoId) {
    throw new Error("Please paste a valid YouTube link.");
  }

  const endpoint = `${TRANSCRIPT_BASE.replace(/\/$/, "")}/${videoId}.txt`;
  let res: Response;
  try {
    res = await fetch(endpoint, {
      method: "GET",
      headers: { Accept: "text/plain, text/markdown, */*" },
      cache: "no-store",
    });
  } catch {
    throw new Error(
      "Could not reach the YouTube transcript service. Please try again in a moment.",
    );
  }

  const text = await res.text();

  if (!res.ok) {
    throw new Error(
      res.status === 429
        ? "YouTube transcript lookup is busy. Please wait a minute and try again."
        : "We could not pull a transcript from that YouTube video. It may have no captions, or the link may be private.",
    );
  }

  const parsed = parseTranscriptAiDocument(text);
  if (!parsed) {
    throw new Error(
      "That video has no usable captions. Try another public video, or upload audio instead.",
    );
  }
  return parsed;
}
